# -*- coding: utf-8 -*-
"""Gera o conteudo de CANTADAS (leves: fofas + engracadas) em assets/frases/.
Escreve index.json (categorias) + {id}.json (array de cantadas). Tudo autoral.
"""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "assets", "frases")
os.makedirs(BASE, exist_ok=True)

CATS = [
    ("romanticas",     "Cantadas Românticas",   "❤️", ["#C9184A", "#FF2E63"]),
    ("engracadas",     "Cantadas Engraçadas",   "😂", ["#F12711", "#F5AF19"]),
    ("de_amor",        "Cantadas de Amor",      "💗", ["#E11D48", "#FF4B6E"]),
    ("para_conquistar","Para Conquistar",       "🎯", ["#FF2E63", "#C9184A"]),
    ("para_ela",       "Para Conquistar Ela",   "👩", ["#FF0080", "#FF8C00"]),
    ("para_ele",       "Para Conquistar Ele",   "👨", ["#8E0E00", "#FF4B2B"]),
    ("flerte",         "Flerte & Paquera",      "😉", ["#FF4B2B", "#B91D73"]),
    ("para_crush",     "Para o Crush",          "💘", ["#FF416C", "#C9184A"]),
    ("fofas",          "Fofas",                 "💕", ["#FF416C", "#FF4B2B"]),
    ("elogios",        "Elogios",               "😍", ["#FF0080", "#FF8C00"]),
    ("atrevidas",      "Atrevidas",             "😏", ["#6A0136", "#FF2E63"]),
    ("indiretas",      "Indiretas",             "🫣", ["#6A0136", "#FF2E63"]),
    ("curtas",         "Curtas",                "✂️", ["#F12711", "#F5AF19"]),
    ("criativas",      "Criativas",             "✨", ["#B91D73", "#F953C6"]),
    ("nerds",          "Nerds & Geek",          "🤓", ["#44107A", "#FF1361"]),
    ("classicas",      "Clássicas",             "⭐", ["#EE0979", "#FF6A00"]),
    ("de_bar",         "De Bar & Balada",       "🍻", ["#FF7A00", "#F5AF19"]),
    ("bom_dia",        "De Bom Dia",            "☀️", ["#FF7A00", "#F5AF19"]),
    ("boa_noite",      "De Boa Noite",          "🌙", ["#44107A", "#FF1361"]),
]

DATA = {
"fofas": [
"Você é a razão do meu sorriso bobo o dia inteiro.",
"Se aconchego fosse pessoa, teria o seu nome.",
"Você é fofo do jeitinho que eu sempre quis abraçar.",
"Meu lugar favorito no mundo é do seu ladinho.",
"Você deixa até os meus dias cinzas coloridos.",
"Queria ser o seu cobertor pra te abraçar a noite toda.",
"Com você, até o silêncio é gostoso.",
"Você é o carinho que eu não sabia que estava procurando.",
"Se eu pudesse, guardava o seu sorriso no bolso.",
"Você é a coisa mais fofa que apareceu na minha vida.",
"Meu coração faz um barulhinho fofo quando você chega.",
"Você é aquele abraço quentinho em forma de gente.",
"Do seu lado, o mundo fica mais macio.",
"Você é o motivo de eu acordar de bom humor.",
"Queria congelar o tempo só pra ficar mais um pouco com você.",
"Você é a fofura que faltava no meu dia.",
"Seu sorriso é o meu docinho preferido.",
"Você me dá aquela vontade de ficar de mãos dadas sem pressa.",
"Com você por perto, tudo fica mais leve.",
"Você é a definição de aconchego pra mim.",
"Meu coração escolheu você sem nem pedir minha permissão.",
"Você é fofo demais pra ser real, mas ainda bem que é.",
"Queria ser motivo do seu sorriso, igual você é do meu.",
"Você é a parte boa de todos os meus dias.",
"Se carinho tivesse rosto, seria o seu.",
"Você é aquele friozinho gostoso na barriga.",
"Do seu lado eu me sinto em casa.",
"Você é a fofura que eu quero na minha rotina.",
"Meu dia só fica completo depois do seu 'oi'.",
"Você é pequeno detalhe que faz toda a diferença em mim.",
"Queria te dar um abraço que durasse o dia inteiro.",
"Você é a ternura em pessoa.",
"Seu jeitinho me desarma toda vez.",
"Você é o meu cantinho preferido do universo.",
"Com você o coração fica quentinho.",
"Você é fofo até quando faz nada, imagina fazendo carinho.",
"Meu sorriso tem CPF e o nome dele é você.",
"Você é a razão de eu olhar o celular sorrindo.",
"Queria embrulhar você pra presente e ficar só pra mim.",
"Você é a fofura que arruma qualquer dia ruim.",
],
"romanticas": [
"Se eu tivesse uma estrela pra cada vez que penso em você, teria o céu inteiro.",
"Você chegou e o mundo fez sentido.",
"Meu coração bate em ritmo de você.",
"Você é o poema que eu não sabia escrever.",
"Se amar você é errado, não quero ter razão.",
"Você é o meu para sempre em forma de pessoa.",
"Meu lugar preferido é dentro de um abraço seu.",
"Você é o motivo de todas as minhas melhores histórias.",
"Se o amor tivesse endereço, seria onde você estivesse.",
"Você é a resposta pra perguntas que eu nem sabia que tinha.",
"Comigo é simples: onde você está, é onde eu quero estar.",
"Você é o tipo de amor que a gente escreve música.",
"Meu coração escolheu e não quer devolução.",
"Você é o sonho que ficou depois que eu acordei.",
"Se existe destino, o meu tinha o seu nome.",
"Você me faz acreditar em coisa que eu jurava não existir.",
"Meu mundo gira, mas sempre volta pra você.",
"Você é a razão de eu acreditar no amor de novo.",
"Contigo, até o comum vira inesquecível.",
"Você é a paz que eu procurava no meio do caos.",
"Meu coração te reconheceu antes mesmo de eu entender.",
"Você é o começo de tudo que eu quero pra mim.",
"Se amar tem preço, eu pago à vista por você.",
"Você é a melhor parte de todos os meus dias.",
"Meu coração tem seu nome escrito em letra bonita.",
"Você é o amor que eu quero envelhecer junto.",
"Do seu lado, o tempo passa e eu nem ligo.",
"Você é a única certeza no meio das minhas dúvidas.",
"Meu coração é seu, e nem quero de volta.",
"Você é o motivo de eu sorrir do nada.",
"Se pudesse pedir um desejo, pediria mais tempo com você.",
"Você é o amor que cabe em uma vida inteira.",
"Contigo eu aprendi que lar é uma pessoa.",
"Você é a razão do meu 'bom dia' virar 'bom demais'.",
"Meu coração não tem GPS, mas sempre acha o caminho até você.",
"Você é a poesia que eu quero ler todo dia.",
"Se o amor fosse cor, o seu pintava o meu mundo.",
"Você é o abraço que resolve qualquer dia difícil.",
"Meu coração te escolheu e bateu o martelo.",
"Você é o para sempre que eu quero começar hoje.",
],
"engracadas": [
"Você é ladrão? Porque roubou minha última bolacha do coração.",
"Seu pai é padeiro? Porque você é um pão... de mel.",
"Perdi meu número, me empresta o seu?",
"Você acredita em amor à primeira vista ou preciso passar de novo?",
"Se beleza desse cadeia, você pegava prisão perpétua.",
"Você é Wi-Fi? Porque senti uma conexão... e agora quero a senha.",
"Me belisca, porque você é bom demais pra ser verdade.",
"Você é Google? Porque tem tudo que eu tava procurando.",
"Cuidado ao andar, senão você tropeça no meu coração caído.",
"Seu nome é Trakinas? Porque abriu e eu já quero.",
"Você é açúcar? Porque tá deixando meu dia doce demais.",
"Me chama de calculadora, porque contigo eu só quero contar.",
"Você é estacionamento? Porque eu quero passar horas aqui.",
"Se você fosse fruta, seria um 'gata-melão'.",
"Você caiu do céu ou pulou pra chamar minha atenção?",
"Me dá seu CEP? Quero saber o caminho pro seu coração.",
"Você é boleto? Porque não sai da minha cabeça (nem da minha conta).",
"Seu sorriso tem garantia? Porque quero um pra vida toda.",
"Você é pizza? Porque eu te quero inteirinha, sem dividir.",
"Me empresta um mapa? Me perdi nos seus olhos.",
"Você é bateria de celular? Porque tá acabando comigo (de amor).",
"Se carência fosse crime, eu tava preso te olhando.",
"Você é semáforo? Porque quando te vejo, eu paro.",
"Me chama de CEP, porque eu quero fazer parte do seu endereço.",
"Você é ar-condicionado? Porque me deixou gelado quando passou.",
"Seu nome é uê-fai? Porque quero ficar conectado a você.",
"Você é lombada? Porque me fez reduzir a velocidade e olhar.",
"Me dá um desconto? Porque tô caro de tão apaixonado.",
"Você é micro-ondas? Porque esquentou meu coração em 30 segundos.",
"Seu pai é agricultor? Porque plantou um jardim no meu coração.",
"Você é espelho? Porque me vejo com você pro resto da vida.",
"Me chama de pilha, porque contigo eu não desligo.",
"Você é cafezinho? Porque me deixou aceso a noite toda.",
"Se você fosse verbo, seria irregular de tão especial.",
"Você é tomada? Porque senti uma corrente entre a gente.",
"Me dá teu horário? Quero marcar o resto da minha vida.",
"Você é elevador? Porque me elevou o astral só de aparecer.",
"Seu nome é geladeira? Porque quero te abrir toda vez que der fome de você.",
"Você é adesivo? Porque grudou na minha mente.",
"Me chama de professor, porque quero dar aula de como te amar.",
],
"criativas": [
"Se cada pensamento seu virasse estrela, o céu ficava pequeno.",
"Você é aquela ideia genial que aparece do nada e muda tudo.",
"Reescrevi o dicionário: agora 'perfeito' tem a sua foto.",
"Você é plot twist da melhor história que eu já vivi.",
"Se o universo fosse um livro, você seria meu capítulo favorito.",
"Você é o detalhe que os artistas passam a vida tentando pintar.",
"Inventei um novo idioma só pra descrever o seu sorriso.",
"Você é a nota que faltava pra minha música ficar completa.",
"Se eu fosse pintor, gastaria todas as cores em você.",
"Você é a metáfora que todo poeta sonha em encontrar.",
"Coloquei você na minha lista de coisas impossíveis de esquecer.",
"Você é o enredo que eu quero que nunca acabe.",
"Se pensamentos fossem mensagens, sua caixa lotava.",
"Você é a fórmula que a ciência ainda não explicou.",
"Reprogramei meu coração: agora ele só roda com você.",
"Você é obra de arte que ganhou vida e resolveu me encontrar.",
"Se a inspiração tivesse rosto, seria o seu.",
"Você é o verso solto que decidiu rimar comigo.",
"Criei um planeta novo só pra morar perto de você.",
"Você é o clique que faltava na minha melhor foto.",
"Se ideias fossem fogos, você seria o grand finale.",
"Você é o rascunho que virou minha melhor versão.",
"Coloquei 'você' como senha de tudo, porque é o que eu não esqueço.",
"Você é o experimento que deu certo de primeira.",
"Se sonhos tivessem trilha sonora, a sua seria minha favorita.",
"Você é a página em branco onde eu quero escrever o futuro.",
"Reinventei a roda só pra ela girar na sua direção.",
"Você é a peça que encaixou no quebra-cabeça que eu era.",
"Se pudesse patentear um sorriso, patenteava o seu.",
"Você é o brainstorm que só teve boas ideias.",
"Coloquei você no modo avião: agora só tenho olhos pra você.",
"Você é o algoritmo que sempre me recomenda felicidade.",
"Se a criatividade fosse rio, você seria minha nascente.",
"Você é o esboço que virou minha obra-prima.",
"Reescrevi meu roteiro e coloquei você em todas as cenas.",
"Você é a invenção que a humanidade ainda vai agradecer.",
"Se cada olhar seu fosse pincelada, eu era uma galeria.",
"Você é o easter egg escondido no melhor jogo da minha vida.",
"Coloquei uma legenda na minha vida: 'depois de você'.",
"Você é a ideia que eu quero desenvolver pra sempre.",
],
"nerds": [
"Você deve ser feito de cobre e telúrio, porque você é Cu-Te.",
"Se você fosse uma variável, seria a constante da minha felicidade.",
"Meu amor por você é exponencial, não tem limite.",
"Você é o meu 100 de vida no jogo mais difícil: a rotina.",
"Sem você, meu código dá erro de compilação.",
"Você é o boss final que eu não quero derrotar, quero namorar.",
"Se amor fosse largura de banda, a nossa seria fibra óptica.",
"Você é o easter egg mais fofo do meu jogo favorito.",
"Meu coração roda em loop infinito por você.",
"Você é a atualização que deixou minha vida mais rápida.",
"Se eu fosse um jogo, você seria minha vida extra.",
"Você é a chave privada que abre o meu coração.",
"Nosso amor tem uptime de 100%, nunca cai.",
"Você é o crossover que eu não sabia que precisava.",
"Se olhar fosse Wi-Fi, o seu tinha o sinal mais forte.",
"Você é o cheat code da minha felicidade.",
"Meu coração deu overclock quando você chegou.",
"Você é a run perfeita: sem bug e sem lag.",
"Se você fosse função, seria a que sempre retorna sorriso.",
"Você é o combo perfeito que eu levei a vida pra descobrir.",
"Meu amor por você não tem cooldown.",
"Você é a expansão que faltava na história da minha vida.",
"Se eu tivesse que salvar um checkpoint, seria ao seu lado.",
"Você é o loot lendário que dropou no meu caminho.",
"Nosso amor é open source: livre e pra sempre.",
"Você é a senha que meu coração nunca esquece.",
"Se cada byte fosse um beijo, eu te daria um terabyte.",
"Você é o respawn do meu bom humor.",
"Meu coração não tem antivírus contra você.",
"Você é a build perfeita que eu não quero mudar.",
"Se amor fosse pixel, você seria 4K.",
"Você é o portal que me leva pro melhor mundo.",
"Meu coração deu 'match' e não quer desfazer.",
"Você é a DLC que deixou minha vida completa.",
"Se você fosse comando, seria Ctrl+Z dos meus dias ruins.",
"Você é o high score que eu nunca vou superar.",
"Nosso amor não precisa de tutorial, veio intuitivo.",
"Você é o power-up que me deixou invencível.",
"Meu coração te deu admin: acesso total.",
"Você é o final feliz que todo bom jogo merece.",
],
"de_bar": [
"Sua beleza fez minha bebida gelada esquentar.",
"Deixa eu adivinhar seu nome: futuro?",
"Se sorriso fosse dose, você me deixava embriagado.",
"Vim aqui só pela cerveja, mas fiquei pelo seu sorriso.",
"Posso te pagar uma bebida ou você prefere ir direto pro plano de vida a dois?",
"Nesse bar cheio, meus olhos só acharam você.",
"Você é o petisco que faltava pra minha noite ficar completa.",
"Se eu fechar a conta, você fecha o dia comigo?",
"Sua risada é a melhor trilha sonora dessa balada.",
"Vim beber pra esquecer, mas agora só quero lembrar de você.",
"Se dançar fosse desculpa, eu inventava uma música só nossa.",
"Você é o brinde que eu quero fazer todas as noites.",
"O bar tá cheio, mas do seu lado sobra espaço pra gente.",
"Sua presença é mais forte que qualquer dose daqui.",
"Se a noite fosse jovem, eu apostava ela toda em você.",
"Você chegou e a balada ficou boa de verdade.",
"Deixa eu te tirar pra dançar antes que outro tenha a boa ideia.",
"Sua beleza não tá no cardápio, mas é a única coisa que eu quero.",
"Se eu perder essa noite, pelo menos ganhei seu sorriso.",
"Você é o motivo de eu não querer ir embora tão cedo.",
"Nessa música lenta, meu único pedido é você.",
"Se cada olhar seu fosse um drink, eu já tava apaixonado.",
"Vim pra pista, mas o melhor lance da noite é você.",
"Sua companhia vale mais que o happy hour inteiro.",
"Se a última música tocar, dança comigo até o fim?",
"Você é o after mais gostoso que essa noite podia ter.",
"Deixa eu adivinhar: você também não veio pela cerveja, né?",
"Sua risada abafou o som do bar inteiro.",
"Se eu te pagar um chopp, você me paga com um sorriso?",
"Você é o brinde que eu quero repetir a noite toda.",
"Nessa multidão, só a sua vibe me chamou.",
"Se dançar colado fosse crime, eu me entregava agora.",
"Você deixou a noite mais interessante que qualquer promoção.",
"Vim beber sozinho, mas do seu lado eu fico bem acompanhado.",
"Se a conta chegar, deixa que eu pago, só fica mais um pouco.",
"Sua energia é o melhor open bar dessa festa.",
"Você é o motivo de eu querer prolongar essa madrugada.",
"Se a balada acabar, a gente continua a noite conversando?",
"Sua presença deixou meu chopp de lado.",
"Você é o encontro que eu não planejei, mas não quero perder.",
],
"elogios": [
"Seu sorriso ilumina qualquer ambiente.",
"Você tem o olhar mais bonito que eu já vi.",
"Sua presença muda o clima de qualquer lugar.",
"Você é bonito por dentro e por fora, e isso é raro.",
"Seu jeito de falar prende qualquer um.",
"Você tem uma beleza que não cansa de olhar.",
"Sua energia contagia todo mundo em volta.",
"Você é o tipo de pessoa que a gente lembra pra sempre.",
"Seu sorriso deveria ser tombado como patrimônio.",
"Você tem um charme que não se aprende, se nasce com ele.",
"Sua voz é a coisa mais gostosa de ouvir.",
"Você é elegante até quando não tá tentando.",
"Seu olhar diz mais que mil palavras.",
"Você tem uma beleza que combina com bom coração.",
"Sua risada é a melhor coisa do meu dia.",
"Você é impossível de passar despercebido.",
"Seu estilo é único, ninguém copia.",
"Você tem um brilho próprio que chama atenção.",
"Sua simpatia conquista qualquer pessoa.",
"Você é bonito de um jeito que fica na memória.",
"Seu sorriso vale mais que qualquer palavra.",
"Você tem a beleza que a foto nunca consegue capturar direito.",
"Sua presença já melhora meu dia inteiro.",
"Você é o tipo de gente que deixa o mundo mais bonito.",
"Seu jeito doce combina com esse rosto lindo.",
"Você tem um magnetismo que não dá pra explicar.",
"Sua elegância aparece até nos gestos simples.",
"Você é bonito e ainda por cima gente boa, é injusto.",
"Seu olhar tem um poder que você nem imagina.",
"Você é a definição de charme natural.",
"Sua beleza vem acompanhada de uma vibe incrível.",
"Você deixa qualquer roupa mais bonita.",
"Seu sorriso desarma qualquer mau humor.",
"Você tem uma luz que atrai todo mundo.",
"Sua confiança te deixa ainda mais atraente.",
"Você é bonito de olhar e melhor ainda de conhecer.",
"Seu jeito de ser é tão bonito quanto o seu rosto.",
"Você tem o dom de deixar tudo mais interessante.",
"Sua beleza é daquelas que marcam época.",
"Você é, sem exagero, a pessoa mais bonita daqui.",
],
"atrevidas": [
"Se eu te chamar pra sair, você já vem decidido a me conquistar?",
"Cuidado com esse olhar, ele tá me deixando sem juízo.",
"Você tem noção do efeito que causa ou finge que não?",
"Se depender de mim, essa conversa não acaba tão cedo.",
"Seu sorriso é perigoso, devia vir com aviso.",
"Tô te avisando: é fácil se apaixonar por você.",
"Se você chegar mais perto, eu não respondo pelas batidas do meu coração.",
"Você mexe comigo de um jeito que nem tá no manual.",
"Adianta eu resistir ou já me rendo agora?",
"Seu charme tá jogando sujo comigo.",
"Se eu piscar, você promete não sumir?",
"Você tem cara de quem vai bagunçar meus planos, e eu tô gostando.",
"Cuidado, porque eu tô a um sorriso seu de me apaixonar.",
"Você é do tipo que a gente olha duas vezes e ainda quer a terceira.",
"Se essa química fosse aula, a gente ia gabaritar.",
"Tô achando que você caprichou só pra me deixar sem jeito.",
"Seu olhar tá me convidando pra um perrengue gostoso.",
"Você chegou e meu autocontrole pediu férias.",
"Se eu te disser o que tô pensando, você cora ou sorri?",
"Você tem toda a pinta de ser a minha melhor má ideia.",
"Cuidado ao sorrir assim, que eu tomo como sinal verde.",
"Você tá deixando difícil eu me comportar.",
"Se depender desse clima, a noite promete.",
"Você é o tipo de tentação que vale a pena.",
"Tô aqui tentando ser sério, mas você não ajuda.",
"Seu jeito atrevido combina demais com o meu.",
"Se você continuar me olhando assim, eu vou ter que agir.",
"Você tem um quê de proibido que me atrai demais.",
"Adianta eu fingir que não reparei em você? Acho que não.",
"Você joga charme e eu já tô perdendo o jogo.",
"Se eu chegar, você recua ou aceita o desafio?",
"Você tem uma energia que mexe com qualquer um, imagina comigo.",
"Tô tentando não sorrir, mas você complica tudo.",
"Seu olhar tem segundas intenções, e eu aprovo.",
"Você é a distração mais gostosa que eu já tive.",
"Se a gente continuar assim, a conversa vai longe.",
"Você chegou chegando, e eu gostei do plano.",
"Cuidado que eu tô ficando viciado nesse seu jeito.",
"Você tem talento pra me deixar sem palavras.",
"Se isso aqui é um jogo, eu quero perder pra você.",
],
"classicas": [
"Seu pai é ladrão? Porque roubou as estrelas e colocou nos seus olhos.",
"Você não está cansado de correr o dia todo pela minha cabeça?",
"Acredita em amor à primeira vista ou preciso passar de novo?",
"Se beleza fosse tempo, você seria a eternidade.",
"Você deve ser um dicionário, porque dá sentido à minha vida.",
"Me perdi... você pode me dar a direção do seu coração?",
"Seu nome é Google? Porque você tem tudo o que eu procuro.",
"Se eu pudesse reorganizar o alfabeto, colocaria o U e o EU juntos.",
"Você caiu do céu? Porque você é um anjo.",
"Deve doer... cair do céu assim, tão perfeito.",
"Se um beijo seu fosse floco de neve, eu te mandaria uma nevasca.",
"Você tem um mapa? Porque me perdi nos seus olhos.",
"Seu sorriso é a oitava maravilha do mundo.",
"Se olhar matasse, o seu me conquistava na hora.",
"Você é a resposta certa pra pergunta que eu nem sabia fazer.",
"Meu coração ligou dizendo que sente sua falta.",
"Se beleza desse multa, você já tava devendo pra mim.",
"Você é como o sol: ilumina tudo por onde passa.",
"Não sou fotógrafo, mas posso nos imaginar juntos.",
"Se eu fosse estrela, brilharia só pra você me notar.",
"Você é doce como mel e raro como diamante.",
"Cansei de procurar minha alma gêmea, aí você apareceu.",
"Seu sorriso poderia acabar com qualquer tristeza.",
"Se o amor fosse um livro, você seria minha história favorita.",
"Você é a razão de eu acreditar em contos de fada.",
"Meus olhos procuraram a vida toda e pararam em você.",
"Se cada estrela fosse um pensamento meu, o céu seria seu.",
"Você tem o dom de deixar tudo mais bonito.",
"Se eu tivesse um desejo, seria te ver sorrir todo dia.",
"Você é o tipo de sonho de que a gente não quer acordar.",
"Seu olhar tem o brilho que eu procurava.",
"Se amor fosse rio, o meu desaguava em você.",
"Você é a melhor coincidência da minha vida.",
"Seu sorriso é a chave do meu bom humor.",
"Se beleza fosse crime, você pegava perpétua.",
"Você é a estrela mais brilhante do meu céu.",
"Meu coração te reconheceu antes de eu entender.",
"Se eu pudesse, passava a vida inteira te olhando.",
"Você é o presente que eu não esperava ganhar.",
"Seu jeito me conquistou sem nem tentar.",
],
"para_crush": [
"Oi crush, meu dia melhora 100% quando você aparece.",
"Se um dia der, queria te levar pra tomar um sorvete.",
"Você não sai da minha cabeça desde que a gente se falou.",
"Confesso: eu curto quando você me responde rapidinho.",
"Toda vez que você posta, eu sorrio antes de curtir.",
"Se eu te chamar pra sair, você topa?",
"Você é o único motivo de eu ficar olhando o celular.",
"Crush, você reparou que a gente combina, ou sou só eu?",
"Queria ter coragem de te dizer o quanto eu te acho incrível.",
"Se depender de mim, essa amizade vira algo mais.",
"Você é o tipo de pessoa que eu queria conhecer melhor.",
"Confessa: você também sente esse clima entre a gente?",
"Meu 'visto' demora porque eu fico pensando na resposta perfeita.",
"Se você me chamasse pra sair, eu ia dizer sim na hora.",
"Crush, seu sorriso é o print que eu não apago.",
"Queria ser o motivo do seu sorriso hoje.",
"Você já reparou o quanto a nossa conversa flui?",
"Se eu pudesse escolher com quem passar o dia, seria você.",
"Confesso que crio expectativa toda vez que você digita.",
"Você é aquele crush que virou plano sério.",
"Queria saber se eu apareço nos seus pensamentos também.",
"Se a gente se conhecesse melhor, tenho certeza que ia dar certo.",
"Crush, você é a melhor notificação do meu dia.",
"Toda música de amor agora me lembra você.",
"Se você topar, eu já sei o lugar perfeito pro nosso primeiro encontro.",
"Você deixou de ser crush e virou vontade de tentar.",
"Confessa que você também dá uma olhadinha no meu perfil.",
"Queria transformar esses 'oi' em algo pra vida toda.",
"Crush, com você até conversa boba fica interessante.",
"Se eu te chamar hoje, você tem plano melhor que eu?",
"Você é o tipo de pessoa que vale a pena arriscar.",
"Confesso que fico feliz demais quando é você quem chama.",
"Queria ser motivo de você sorrir olhando o celular.",
"Crush, a gente ia formar um casal e tanto.",
"Se rolar, prometo caprichar no primeiro encontro.",
"Você virou aquele nome que eu procuro primeiro na tela.",
"Confessa que a gente tem uma química diferente.",
"Queria saber se você sente esse friozinho na barriga também.",
"Crush, tô aqui torcendo pra você me dar uma chance.",
"Se eu pudesse dar um match na vida real, seria com você.",
],
}

EXTRA = {
"fofas": [
"Você é o abraço que eu queria ter guardado o dia inteiro.",
"Se fofura fosse dose, você era overdose.",
"Você é meu docinho de todo dia.",
"Queria ser a sua playlist favorita e tocar o dia todo pra você.",
"Você deixa tudo mais gostosinho de viver.",
"Meu coração faz 'aww' toda vez que você aparece.",
"Você é a coisa mais fofa entre todas as fofuras.",
"Seu sorriso é meu detox de dia ruim.",
"Você é aquele cobertor quentinho em dia de frio.",
"Queria te dar um aperto e não soltar mais.",
"Você é fofo até no jeito de digitar.",
"Meu dia rende mais depois de um 'oi' seu.",
"Você é o carinho que eu não sabia que precisava.",
"Se eu pudesse, colecionava sorrisos seus.",
"Você é a fofura oficial da minha vida.",
"Seu jeitinho me derrete todinho.",
"Você é o motivo do meu sorriso automático.",
"Queria ser motivo do seu bom humor todo dia.",
"Você é aquele docinho que a gente quer repetir.",
"Meu coração bate mais fofinho quando é você.",
"Você é a definição de 'gracinha'.",
"Se aconchego morasse em alguém, seria em você.",
"Você é fofo demais pra ser só amigo.",
"Queria pausar o mundo pra ficar te olhando.",
"Você é o meu tipo favorito de fofura.",
],
"romanticas": [
"Você é o verso que faltava no poema da minha vida.",
"Meu coração escolheu você e não aceita troca.",
"Você é o motivo de eu acreditar em pra sempre.",
"Se o amor fosse rota, todas levariam até você.",
"Você é o abraço que virou o meu lar.",
"Meu mundo ganhou cor no dia em que você chegou.",
"Você é a paz no meio da minha correria.",
"Se eu pudesse, envelhecia a vida toda ao seu lado.",
"Você é o sonho que ficou depois que acordei.",
"Meu coração te achou antes de eu entender o porquê.",
"Você é a melhor história que eu quero contar pra sempre.",
"Se amar você é vício, eu não quero cura.",
"Você é a razão do meu sorriso sem motivo.",
"Meu coração tem o seu nome em letra bonita.",
"Você é o para sempre que eu quero começar agora.",
"Contigo, até o silêncio vira poesia.",
"Você é a única certeza no meio das minhas dúvidas.",
"Meu coração é seu, e nem quero de volta.",
"Você é o amor que eu quero na primeira e na última página.",
"Se pudesse pedir um desejo, pediria mais você.",
"Você é a melhor coisa que já aconteceu comigo.",
"Meu coração não tem mapa, mas sempre acha você.",
"Você é a poesia que eu leio todo dia sem cansar.",
"Se o amor fosse cor, o seu pintava meu mundo.",
"Você é o meu lar em forma de pessoa.",
],
"engracadas": [
"Você é boleto? Porque não me sai da cabeça.",
"Seu nome é uê-fai? Porque tô sentindo a conexão.",
"Você é micro-ondas? Esquentou meu coração em 10 segundos.",
"Me chama de garçom, porque eu tô a fim de te servir.",
"Você é cafezinho? Me deixou ligado a noite toda.",
"Seu pai é pedreiro? Porque você construiu um castelo no meu coração.",
"Você é fila de banco? Porque eu esperaria horas por você.",
"Me dá um Ctrl+C, porque quero você em todo lugar.",
"Você é bateria fraca? Porque tá acabando comigo de amor.",
"Seu nome é Domingo? Porque eu descanso quando te vejo.",
"Você é promoção? Porque eu não posso perder.",
"Me chama de GPS, porque eu te levo a qualquer lugar.",
"Você é lombada? Me fez frear e reparar em você.",
"Seu sorriso tem nota fiscal? Porque quero garantia vitalícia.",
"Você é pipoca? Porque eu não consigo parar.",
"Me empresta um guarda-chuva? Tô chovendo elogios por você.",
"Você é elevador? Me elevou o astral só de aparecer.",
"Seu nome é feriado? Porque todo mundo te espera.",
"Você é adesivo? Grudou na minha mente.",
"Me chama de despertador, porque eu acordo pensando em você.",
"Você é semáforo? Porque quando te vejo eu paro.",
"Seu pai é confeiteiro? Porque você é um docinho.",
"Você é tomada? Senti uma corrente entre a gente.",
"Me dá seu horário? Quero agendar o resto da vida.",
"Você é geladeira? Porque quero te abrir toda vez que der fome de amor.",
],
"criativas": [
"Você é o easter egg escondido no melhor jogo da vida.",
"Reescrevi meu roteiro e coloquei você em todas as cenas.",
"Você é a ideia genial que apareceu do nada e mudou tudo.",
"Se inspiração tivesse rosto, seria o seu.",
"Você é o plot twist da minha melhor história.",
"Inventei uma cor nova só pra descrever você.",
"Você é a peça que faltava no meu quebra-cabeça.",
"Coloquei 'você' como legenda de todos os meus dias bons.",
"Você é a metáfora que todo poeta sonha achar.",
"Se pensamentos fossem estrelas, o céu seria seu.",
"Você é o esboço que virou minha obra-prima.",
"Reprogramei meu coração: agora ele só roda com você.",
"Você é o verso solto que resolveu rimar comigo.",
"Criei um universo novo só pra morar perto de você.",
"Você é a fórmula que a ciência não explica.",
"Se ideias fossem fogos, você era o grand finale.",
"Você é a página em branco onde eu quero escrever o futuro.",
"Coloquei você no modo destaque da minha vida.",
"Você é o experimento que deu certo de primeira.",
"Reinventei a roda só pra ela girar na sua direção.",
"Você é a invenção que a humanidade vai agradecer.",
"Se sonhos tivessem trilha, a sua seria a minha favorita.",
"Você é o rascunho que virou minha melhor versão.",
"Coloquei uma placa na minha vida: 'depois de você'.",
"Você é a ideia que eu quero desenvolver pra sempre.",
],
"nerds": [
"Você é a atualização que deixou minha vida mais rápida.",
"Meu amor por você não tem cooldown.",
"Você é o loot lendário que dropou no meu caminho.",
"Se você fosse função, seria a que sempre retorna sorriso.",
"Você é o checkpoint que eu quero salvar pra sempre.",
"Meu coração deu match e não quer desfazer.",
"Você é o power-up que me deixou invencível.",
"Se amor fosse pixel, você seria 8K.",
"Você é o final feliz que todo bom jogo merece.",
"Meu coração roda em loop infinito por você.",
"Você é o cheat code da minha felicidade.",
"Sem você, meu código dá erro de compilação.",
"Você é a run perfeita: sem bug e sem lag.",
"Se olhar fosse Wi-Fi, o seu tinha o sinal mais forte.",
"Você é o respawn do meu bom humor.",
"Meu coração deu overclock quando você chegou.",
"Você é a DLC que deixou minha vida completa.",
"Se cada byte fosse um beijo, eu te daria um petabyte.",
"Você é o high score que eu nunca vou superar.",
"Nosso amor tem uptime de 100%.",
"Você é a build perfeita que eu não quero mudar.",
"Meu coração te deu acesso admin.",
"Você é o boss final que eu só quero namorar.",
"Se eu fosse jogo, você seria minha vida extra.",
"Você é o combo perfeito que levei a vida pra descobrir.",
],
"de_bar": [
"Se eu fechar a conta, você fecha a noite comigo?",
"Nesse bar cheio, só a sua vibe me chamou.",
"Você é o brinde que eu quero repetir a noite toda.",
"Deixa eu te tirar pra dançar antes que outro tenha a ideia.",
"Sua risada abafou o som do bar inteiro.",
"Vim beber pra esquecer, mas agora só quero lembrar de você.",
"Se a última música tocar, dança comigo até o fim?",
"Você é o after mais gostoso que essa noite podia ter.",
"Sua presença vale mais que o happy hour inteiro.",
"Se cada olhar seu fosse um drink, eu já tava apaixonado.",
"Você é o motivo de eu não querer ir embora.",
"Nessa música lenta, meu único pedido é você.",
"Deixa eu adivinhar: você também não veio pela cerveja.",
"Sua energia é o melhor open bar da festa.",
"Se a conta chegar, deixa comigo, só fica mais um pouco.",
"Você deixou a noite mais interessante que qualquer promoção.",
"Vim pra pista, mas o melhor lance da noite é você.",
"Sua companhia é o petisco que faltava.",
"Se rolar, a gente continua a madrugada conversando?",
"Você é o encontro que eu não planejei e não quero perder.",
"Sua beleza não tá no cardápio, mas é tudo que eu quero.",
"Deixa eu te pagar uma bebida ou vamos direto ao date?",
"Você é o brinde perfeito pra qualquer noite.",
"Nessa multidão, meus olhos só acharam você.",
"Se dançar colado fosse crime, eu me entregava agora.",
],
"elogios": [
"Sua confiança te deixa ainda mais atraente.",
"Você tem um brilho que ninguém copia.",
"Seu olhar tem um poder que você nem imagina.",
"Você deixa qualquer lugar mais bonito.",
"Sua risada é a melhor coisa do meu dia.",
"Você tem um charme que não se aprende, se nasce com ele.",
"Seu sorriso deveria ser tombado como patrimônio.",
"Você é bonito e ainda gente boa, é injusto.",
"Sua elegância aparece até nos gestos simples.",
"Você tem uma beleza que não cansa de olhar.",
"Seu jeito doce combina com esse rosto lindo.",
"Você tem um magnetismo que não dá pra explicar.",
"Sua voz é a coisa mais gostosa de ouvir.",
"Você é impossível de passar despercebido.",
"Seu estilo é único, ninguém alcança.",
"Você tem o dom de deixar tudo mais interessante.",
"Sua presença já melhora meu dia inteiro.",
"Você é bonito de um jeito que fica na memória.",
"Seu olhar diz mais que mil palavras.",
"Você tem uma luz que atrai todo mundo.",
"Sua simpatia conquista qualquer pessoa.",
"Você é, sem exagero, a pessoa mais bonita daqui.",
"Seu sorriso desarma qualquer mau humor.",
"Você tem uma beleza que combina com bom coração.",
"Sua energia contagia todo mundo em volta.",
],
"atrevidas": [
"Se você continuar me olhando assim, eu vou ter que agir.",
"Você tem um quê de proibido que me atrai demais.",
"Cuidado que eu tô ficando viciado nesse seu jeito.",
"Você é a distração mais gostosa que eu já tive.",
"Se isso aqui é um jogo, eu quero perder pra você.",
"Você joga charme e eu já tô perdendo o controle.",
"Tô tentando me comportar, mas você não ajuda.",
"Seu olhar tem segundas intenções, e eu aprovo.",
"Você chegou chegando, e eu gostei do plano.",
"Se depender desse clima, a noite promete.",
"Você tem talento pra me deixar sem palavras.",
"Cuidado ao sorrir assim, que eu tomo como sinal verde.",
"Você é o tipo de tentação que vale a pena.",
"Tô achando que você caprichou só pra me provocar.",
"Seu jeito atrevido combina demais com o meu.",
"Se eu chegar, você recua ou aceita o desafio?",
"Você tem uma energia que mexe com qualquer um.",
"Adianta eu resistir ou já me rendo agora?",
"Você mexe comigo de um jeito que nem tá no manual.",
"Se a gente continuar assim, isso vai longe.",
"Você tá deixando difícil eu me comportar.",
"Cuidado, porque eu tô a um sorriso seu de me apaixonar.",
"Você tem toda a pinta da minha melhor má ideia.",
"Se eu te disser o que penso, você cora ou sorri?",
"Você é a tentação mais gostosa da minha lista.",
],
"classicas": [
"Se beleza fosse tempo, você seria a eternidade.",
"Você deve ser um dicionário, porque dá sentido à minha vida.",
"Me perdi... me dá a direção do seu coração?",
"Seu nome é Google? Porque você tem tudo o que eu procuro.",
"Se eu reorganizasse o alfabeto, juntava o U e o EU.",
"Você caiu do céu? Porque você é um anjo.",
"Deve doer cair do céu assim, tão perfeito.",
"Você tem um mapa? Me perdi nos seus olhos.",
"Seu sorriso é a oitava maravilha do mundo.",
"Se olhar matasse, o seu me conquistava na hora.",
"Meu coração ligou dizendo que sente sua falta.",
"Você é como o sol: ilumina tudo por onde passa.",
"Não sou fotógrafo, mas posso nos imaginar juntos.",
"Você é doce como mel e raro como diamante.",
"Cansei de procurar minha alma gêmea, aí você apareceu.",
"Se o amor fosse um livro, você seria minha história favorita.",
"Meus olhos procuraram a vida toda e pararam em você.",
"Se cada estrela fosse um pensamento meu, o céu seria seu.",
"Você é o presente que eu não esperava ganhar.",
"Seu jeito me conquistou sem nem tentar.",
"Se beleza desse multa, você já me devia muito.",
"Você é a estrela mais brilhante do meu céu.",
"Meu coração te reconheceu antes de eu entender.",
"Se eu pudesse, passava a vida te olhando.",
"Você é a melhor coincidência da minha vida.",
],
"para_crush": [
"Crush, você é a melhor notificação do meu dia.",
"Se eu te chamar hoje, você tem plano melhor que eu?",
"Você virou aquele nome que eu procuro primeiro na tela.",
"Confessa que a gente tem uma química diferente.",
"Queria saber se você sente esse friozinho na barriga também.",
"Crush, tô torcendo pra você me dar uma chance.",
"Se eu pudesse dar match na vida real, seria com você.",
"Você deixou de ser crush e virou vontade de tentar.",
"Toda música de amor agora me lembra você.",
"Se você topar, já sei o lugar do nosso primeiro date.",
"Crush, com você até conversa boba fica interessante.",
"Queria ser motivo de você sorrir olhando o celular.",
"Confesso que fico feliz demais quando é você quem chama.",
"Você é o tipo de pessoa que vale a pena arriscar.",
"Crush, a gente ia formar um casal e tanto.",
"Se rolar, prometo caprichar no primeiro encontro.",
"Meu 'visto' demora porque eu penso na resposta perfeita.",
"Você já reparou o quanto a nossa conversa flui?",
"Se a gente se conhecesse melhor, ia dar certo.",
"Crush, seu sorriso é o print que eu não apago.",
"Queria transformar esses 'oi' em algo pra vida toda.",
"Confessa que você também dá uma olhadinha no meu perfil.",
"Você é o único motivo de eu ficar no celular.",
"Se você me chamasse pra sair, eu dizia sim na hora.",
"Crush, meu dia melhora 100% quando você aparece.",
],
}

DATA_NEW = {
"de_amor": [
"Meu amor por você não cabe em uma cantada, mas eu tento todo dia.",
"Se amar você é destino, eu abraço o meu sem reclamar.",
"Você é o amor que eu procurava sem saber o endereço.",
"Meu coração bate teu nome em cada batida.",
"Você é a razão de eu acreditar que o amor existe.",
"Se o amor fosse casa, a minha teria você em cada cômodo.",
"Você é o meu 'pra sempre' começando agora.",
"Amar você é a coisa mais fácil que eu já fiz.",
"Você é o amor que eu quero na primeira e na última página.",
"Meu coração te escolheu e não quer reembolso.",
"Você é o motivo do meu sorriso quando ninguém tá vendo.",
"Se eu pudesse, te amava em todas as vidas possíveis.",
"Você é o amor que acalma e incendeia ao mesmo tempo.",
"Meu mundo faz sentido quando você está nele.",
"Você é a melhor história de amor que eu quero contar.",
"Se amor é escolha, eu te escolho todos os dias.",
"Você é o meu lar em forma de sentimento.",
"Meu coração é seu desde o primeiro 'oi'.",
"Você é o amor que eu não sabia que merecia.",
"Se eu tivesse um coração a mais, também seria seu.",
"Você é a paz e a paixão que eu procurava.",
"Amar você virou meu hobby favorito.",
"Você é o poema que meu coração escreve sozinho.",
"Meu amor por você cresce igual fogo: não para.",
"Você é o pedaço que faltava no meu peito.",
"Se amar você é loucura, então eu quero enlouquecer.",
"Você é o amor que eu quero envelhecer junto.",
"Meu coração é uma carta de amor endereçada a você.",
"Você é a razão de todas as minhas canções preferidas.",
"Se o amor tem cor, o meu é da cor do seu sorriso.",
"Você é o amor que transforma dia comum em especial.",
"Meu coração tropeçou em você e não quer se levantar.",
"Você é a certeza no meio de todas as minhas dúvidas.",
"Amar você é o melhor plano que eu já fiz sem planejar.",
"Você é o amor que vale cada risco.",
"Se eu pudesse pedir só uma coisa, pediria seu coração.",
"Você é o amor que faz meu peito quentinho.",
"Meu amor por você é do tipo que não tem prazo de validade.",
"Você é a melhor parte de todos os meus dias.",
"Se amar você é vício, eu não quero cura nenhuma.",
"Você é o amor que eu escrevo em todas as minhas metas.",
"Meu coração te pertence, e ele não quer voltar.",
"Você é a razão de eu acreditar em final feliz.",
"Amar você é fácil; difícil é não te amar demais.",
"Você é o meu amor à primeira, segunda e milésima vista.",
],
"para_conquistar": [
"Eu não tenho as melhores palavras, mas tenho a melhor intenção: te conquistar.",
"Me dá uma chance e eu te mostro como é ser prioridade.",
"Se você me deixar, eu conquisto seu coração devagarinho.",
"Não quero te impressionar, quero te conquistar de verdade.",
"Topa deixar eu ser o motivo do seu sorriso a partir de hoje?",
"Eu não desisto fácil, ainda mais de alguém como você.",
"Me deixa entrar na sua vida e eu prometo caprichar.",
"Se conquistar você for um desafio, é o meu favorito.",
"Eu já sei: você vale cada esforço pra te conquistar.",
"Me dá seu tempo e eu te dou os meus melhores dias.",
"Quero te conquistar sem pressa, do jeito certo.",
"Aposto que a gente combina — me deixa provar?",
"Eu não quero ser mais um, quero ser o certo pra você.",
"Se você abrir a porta, eu cuido do resto.",
"Prometo conquistar você todo dia, não só no começo.",
"Me deixa te mostrar como é ser bem cuidado.",
"Eu tenho um plano: te fazer feliz. Topa participar?",
"Quero conquistar não só um date, mas o seu coração.",
"Se depender de mim, você não vai querer outro.",
"Me dá a chance e eu viro o melhor 'sim' da sua vida.",
"Vou te conquistar com atitude, não só com palavra bonita.",
"Você merece alguém que corre atrás — e eu corro.",
"Deixa eu ser a boa surpresa que faltava na sua vida.",
"Eu não vim brincar, vim te conquistar de verdade.",
"Se você me der espaço, eu construo algo bonito com você.",
"Quero ganhar seu coração no detalhe, no dia a dia.",
"Me deixa provar que sou diferente do que você já viu.",
"Eu topo o desafio de fazer você se apaixonar.",
"Prometo ser motivo de história boa pra você contar.",
"Se conquistar é uma arte, quero pintar meu melhor quadro em você.",
"Me dá um voto de confiança e eu não te decepciono.",
"Quero te conquistar com verdade, sem joguinho.",
"Você é o tipo de pessoa por quem vale a pena insistir.",
"Deixa eu te mostrar que carinho de verdade ainda existe.",
"Eu não quero te impressionar hoje, quero te ter amanhã.",
"Se você topar, eu transformo 'talvez' em 'com certeza'.",
"Vou conquistar seu coração no capricho, um dia de cada vez.",
"Me dá a deixa e eu faço você se sentir especial sempre.",
"Você merece ser conquistado todos os dias — deixa comigo.",
"Prometo ser o melhor 'sim' que você já disse.",
],
"para_ela": [
"Você é o tipo de mulher que faz qualquer um perder a linha.",
"Nenhuma flor chega perto da sua beleza.",
"Você é elegante, linda e ainda inteligente — combinação perigosa.",
"Se sorriso de mulher fosse arte, o seu era obra-prima.",
"Você tem uma beleza que ilumina qualquer ambiente.",
"Confesso: você é a mulher mais encantadora que eu já vi.",
"Seu jeito de mulher forte me conquistou na hora.",
"Você é o tipo de mulher que a gente admira e se apaixona.",
"Nenhum poema faz jus à mulher linda que você é.",
"Você tem a beleza e a atitude — é impossível não reparar.",
"Seu olhar de mulher decidida me deixou sem chão.",
"Você é linda de um jeito que fica na memória.",
"Toda mulher é especial, mas você é rara.",
"Seu sorriso de mulher conquista sem esforço.",
"Você é a mulher que qualquer um teria orgulho de ter ao lado.",
"Sua elegância de mulher me desarma toda vez.",
"Você é bonita, mas seu charme de mulher é irresistível.",
"Nenhuma paisagem é tão bonita quanto o seu sorriso.",
"Você é a mulher dos sonhos que virou realidade.",
"Seu jeito de mulher independente me atrai demais.",
"Você tem a graça que só uma mulher confiante tem.",
"Se beleza de mulher desse prêmio, você levava todos.",
"Você é encantadora do jeitinho que eu sempre admirei.",
"Sua presença de mulher muda o clima de qualquer lugar.",
"Você é linda por fora e ainda mais por dentro.",
"Toda mulher brilha, mas você ofusca.",
"Seu olhar de mulher segura me conquistou de vez.",
"Você é a definição de mulher poderosa e encantadora.",
"Nenhuma estrela brilha como você quando sorri.",
"Você é o tipo de mulher que marca a vida de alguém.",
"Sua beleza de mulher vem com uma vibe que apaixona.",
"Você é linda, mas sua atitude de mulher é o que me pega.",
"Seu charme de mulher é impossível de ignorar.",
"Você é a mulher que faz o coração acelerar sem avisar.",
"Sua doçura de mulher combina com esse rosto lindo.",
"Você é encantadora, e disso você nem precisa se esforçar.",
"Toda mulher tem seu brilho, o seu é ofuscante.",
"Você é a mulher mais linda dessa e de qualquer sala.",
"Seu jeito de mulher me fez querer te conhecer inteira.",
"Você é linda, forte e doce — o pacote completo.",
],
"para_ele": [
"Você é o tipo de homem que faz qualquer uma olhar duas vezes.",
"Nenhum herói de filme chega perto do seu charme.",
"Você é bonito, gente boa e ainda inteligente — raridade.",
"Seu jeito de homem confiante me conquistou na hora.",
"Você tem uma presença de homem que impõe respeito e atrai.",
"Confesso: você é o homem mais interessante que eu já vi.",
"Seu sorriso de homem seguro desarma qualquer uma.",
"Você é o tipo de homem que a gente admira e se apaixona.",
"Nenhum elogio faz jus ao homem incrível que você é.",
"Você tem a beleza e a atitude — impossível não reparar.",
"Seu olhar de homem decidido me deixou sem chão.",
"Você é bonito de um jeito que fica na memória.",
"Todo homem é especial, mas você é diferente.",
"Seu jeito de homem tranquilo conquista sem esforço.",
"Você é o homem que qualquer uma teria orgulho de ter ao lado.",
"Sua elegância de homem me desarma toda vez.",
"Você é bonito, mas seu charme de homem é irresistível.",
"Você é o homem dos sonhos que resolveu aparecer.",
"Seu jeito de homem parceiro me atrai demais.",
"Você tem a segurança que só um homem confiante tem.",
"Se charme de homem desse prêmio, você levava todos.",
"Você é encantador do jeitinho que eu sempre admirei.",
"Sua presença de homem muda o clima de qualquer lugar.",
"Você é bonito por fora e ainda melhor por dentro.",
"Todo homem tem seu brilho, o seu chama atenção.",
"Seu olhar de homem seguro me conquistou de vez.",
"Você é a definição de homem charmoso e gente fina.",
"Você é o tipo de homem que marca a vida de alguém.",
"Sua vibe de homem tranquilo apaixona sem tentar.",
"Você é bonito, mas sua atitude de homem é o que me pega.",
"Seu charme de homem é impossível de ignorar.",
"Você é o homem que faz o coração acelerar sem avisar.",
"Sua parceria de homem combina com esse sorriso.",
"Você é encantador, e nem precisa se esforçar pra isso.",
"Você é o homem mais interessante dessa e de qualquer roda.",
"Seu jeito de homem me fez querer te conhecer melhor.",
"Você é bonito, forte e gente boa — o pacote completo.",
"Nenhum galã se compara ao seu jeito de ser.",
"Você é o homem que toda conversa fica melhor por perto.",
],
"flerte": [
"Tô te olhando desde que você chegou, e não é por acaso.",
"Se isso aqui é flerte, então eu tô adorando jogar.",
"Confessa: você também tá sentindo esse clima, né?",
"Adianta eu piscar ou você já entendeu o recado?",
"Tô a fim de te conhecer melhor, e você?",
"Esse seu sorriso tá jogando charme direto em mim.",
"Se paquera fosse esporte, a gente ia pro pódio juntos.",
"Você reparou que a gente troca olhar sem querer?",
"Deixa eu adivinhar: você também tá curtindo essa conversa.",
"Tô flertando, sim — e não vou nem disfarçar.",
"Se você sorrir mais uma vez assim, eu me rendo.",
"A gente tá naquele clima gostoso de quem quer se conhecer.",
"Você tem um jeito de flertar que me pegou de jeito.",
"Confessa que esses olhares não são só coincidência.",
"Tô achando esse flerte a melhor parte do meu dia.",
"Se depender de mim, esse papo não acaba tão cedo.",
"Você joga charme e eu já entro no jogo na hora.",
"Adoro uma boa paquera, ainda mais com você.",
"Tá rolando um flerte aqui e eu não quero que pare.",
"Você tem uma vibe que dá vontade de paquerar sem parar.",
"Se isso é só o começo, imagina a gente se conhecendo.",
"Tô te dando indireta faz tempo, capta aí.",
"Esse flerte tá me deixando de bom humor o dia todo.",
"Você é o tipo de paquera que vira algo sério rapidinho.",
"Confessa que você também dá aquela olhadinha, né?",
"A gente flertando assim já é meio caminho pra um date.",
"Tô adorando esse joguinho de olhares com você.",
"Se paquera tivesse nota, a nossa seria dez.",
"Você tem talento pra flertar sem nem perceber.",
"Deixa esse flerte virar convite pra sair?",
"Tô flertando descaradamente e sem nenhum arrependimento.",
"Você deixou o meu dia com gostinho de paquera boa.",
"Se a gente continuar assim, vai dar namoro.",
"Adoro quando o flerte é recíproco — e o nosso é.",
"Você é a melhor paquera que apareceu por aqui.",
"Esse clima de flerte com você tá viciante.",
"Tô te paquerando e torcendo pra você paquerar de volta.",
"Se flertar é arte, com você eu viro artista.",
"Você tem um jeito de paquerar que me desarma.",
"Deixa esse flerte ser o começo de algo bom?",
],
"indiretas": [
"Alguém aqui tá pensando em você, mas não vou dizer quem.",
"Se a carapuça servir, é porque a indireta era pra você mesmo.",
"Tem uma pessoa ocupando minha cabeça, e ela sabe quem é.",
"Não vou marcar ninguém, mas quem entendeu, entendeu.",
"Indireta boa é a que só uma pessoa entende — e é você.",
"Tô a fim de alguém, mas a pessoa finge que não percebe.",
"Se você tá lendo isso e sorrindo, era pra você mesmo.",
"Alguém aqui merece um date comigo, e não sou eu que digo.",
"A indireta é sutil, mas o recado é bem direto.",
"Tem gente que devia tomar coragem — e essa gente é você.",
"Não é indireta, é convite disfarçado. Capta.",
"Se eu mandar mais óbvio que isso, vira declaração.",
"Alguém tá esperando um 'oi' seu e finge que não.",
"A indireta tá aqui, agora é com você entender.",
"Tem uma pessoa que eu não tiro da cabeça, adivinha quem.",
"Se essa indireta te achou, é porque o destino quis.",
"Não vou falar nome, mas meu coração já falou.",
"Quem gosta manda indireta; quem é corajoso responde.",
"A pessoa certa vai ler isso e entender tudo.",
"Tô mandando sinal faz tempo, hora de você captar.",
"Indireta é assim: quem tem que entender, entende na hora.",
"Se coçou aí, é porque a indireta era sua mesmo.",
"Alguém aqui tá esperando você tomar a iniciativa.",
"Não é pra qualquer um, é pra uma pessoa específica.",
"A indireta foi lançada, agora é torcer pra dar certo.",
"Tem alguém pensando em você agora — pista: sou eu.",
"Se você entendeu, meio caminho pro date já andou.",
"Mando indireta porque direto eu fico sem jeito.",
"A pessoa que eu gosto vai ler e fingir que não é ela.",
"Indireta certeira é a que faz a pessoa sorrir escondido.",
"Se seu coração acelerou, era pra você mesmo.",
"Tem um convite escondido nessa mensagem, procura aí.",
"Alguém tá na torcida pra você chegar junto.",
"Não vou entregar, mas essa indireta tem endereço certo.",
"Quem entendeu já sabe que a próxima é um date.",
"A indireta é discreta, mas a vontade de te ver não é.",
"Se você suspeitou, parabéns: era você mesmo.",
"Mando indireta hoje pra ter coragem de ser direto amanhã.",
"A pessoa dessa indireta é linda e tá lendo agora.",
"Capta a indireta antes que eu perca a coragem.",
],
"curtas": [
"Você é meu tipo.",
"Cê é linda demais.",
"Tô caidinho por você.",
"Você me ganhou.",
"Só penso em você.",
"Cê é perfeito.",
"Meu crush é você.",
"Você é tudo.",
"Fiquei no seu sorriso.",
"Cê me encanta.",
"Você é raro.",
"Meu coração é seu.",
"Cê é meu vício.",
"Te quero, simples assim.",
"Você me pega.",
"Cê é meu sim.",
"Só tenho olhos pra você.",
"Você me desmonta.",
"Cê é meu plano.",
"Te achei, enfim.",
"Você é meu barato.",
"Meu bem é você.",
"Cê brilha demais.",
"Você me acende.",
"Tô a fim de você.",
"Cê é meu match.",
"Você me completa.",
"Meu sorriso é você.",
"Cê é meu destino.",
"Você me domina.",
"Te quero perto.",
"Cê é minha vibe.",
"Você é meu clique.",
"Meu foco é você.",
"Cê é meu mundo.",
"Você me inspira.",
"Tô te namorando na mente.",
"Cê é meu presente.",
"Você é a resposta.",
"Meu coração escolheu você.",
],
"bom_dia": [
"Bom dia! Meu único plano hoje é te conquistar.",
"Acordei pensando em você — e isso já fez meu dia.",
"Bom dia pra você que é o motivo do meu sorriso ao acordar.",
"Se cada bom dia fosse um beijo, eu te mandava mil.",
"Bom dia! Você é a melhor notícia da minha manhã.",
"Meu café ficou mais doce só de pensar em você.",
"Bom dia pra pessoa mais linda que vai ler isso.",
"Acordar sabendo que você existe já me deixa feliz.",
"Bom dia! Que tal começar o dia me deixando te paquerar?",
"Você é o sol que faltava pra iluminar minha manhã.",
"Bom dia! Meu coração já acordou chamando seu nome.",
"Se bom dia fosse abraço, o meu apertava você forte.",
"Bom dia pra você que invadiu meus pensamentos matinais.",
"Acordei com vontade de te ver — bom dia, crush.",
"Bom dia! Você deixa até segunda-feira valer a pena.",
"Meu melhor bom dia é o que começa pensando em você.",
"Bom dia! Seu sorriso seria o melhor café da manhã.",
"Que seu dia seja lindo — quase tão lindo quanto você.",
"Bom dia pra pessoa que eu queria acordar do lado.",
"Acordei e a primeira coisa boa foi lembrar de você.",
"Bom dia! Você é meu motivo favorito pra sair da cama.",
"Se manhã tem cor, a minha é da cor do seu sorriso.",
"Bom dia! Já tô contando as horas pra te ver.",
"Meu bom dia só fica completo depois do seu 'oi'.",
"Bom dia pra você que deixa meus dias mais quentes.",
"Acordei apaixonado — e a culpa é toda sua. Bom dia!",
"Bom dia! Que hoje eu tenha coragem de te chamar pra sair.",
"Você é a melhor forma de começar qualquer manhã.",
"Bom dia! Meu coração mandou um recado: sente sua falta.",
"Se eu pudesse, te dava um bom dia com beijo na testa.",
"Bom dia pra pessoa que ilumina meus pensamentos.",
"Acordei sorrindo — adivinha por quê? Bom dia, você.",
"Bom dia! Seu sorriso vale mais que qualquer despertador.",
"Que seu dia comece com a energia boa que você me passa.",
"Bom dia! Você é o motivo do meu bom humor matinal.",
"Meu dia já começou bem: pensei em você primeiro.",
"Bom dia pra você que faz meu coração acordar acelerado.",
"Se bom dia fosse música, a sua seria a minha favorita.",
"Bom dia! Prometo deixar seu dia mais gostoso, se você deixar.",
"Acordei com uma certeza: quero você nas minhas manhãs.",
],
"boa_noite": [
"Boa noite! Vou dormir, mas você continua nos meus pensamentos.",
"Se dormir fosse te encontrar, eu dormia agora mesmo.",
"Boa noite pra você que é o último pensamento do meu dia.",
"Meu travesseiro tá com ciúme de tanto eu pensar em você.",
"Boa noite! Que você sonhe comigo, que eu já sonho com você.",
"A melhor parte da noite é mandar boa noite pra você.",
"Boa noite! Vou fechar os olhos e imaginar a gente junto.",
"Se cada estrela fosse um pensamento meu, o céu era todo seu.",
"Boa noite pra pessoa que deixa minhas noites mais quentes.",
"Vou dormir sorrindo — culpa sua. Boa noite, crush.",
"Boa noite! Meu coração pediu pra dar um oi antes de dormir.",
"Se boa noite fosse abraço, o meu duraria a madrugada.",
"Boa noite pra você que invade meus sonhos sem pedir licença.",
"A lua tá linda, mas nem chega perto do seu sorriso.",
"Boa noite! Queria te desejar isso com um beijo.",
"Meu último pensamento do dia tem nome, e é o seu.",
"Boa noite! Que a saudade te faça sonhar comigo.",
"Se eu pudesse, te dava boa noite de mãos dadas.",
"Boa noite pra pessoa que faz meu coração acelerar até dormindo.",
"Vou dormir, mas antes: você é especial demais.",
"Boa noite! A noite fica melhor sabendo que você existe.",
"Que seus sonhos sejam bons — de preferência comigo neles.",
"Boa noite pra você que ilumina até a minha madrugada.",
"Meu coração não desliga: continua pensando em você.",
"Boa noite! Prometo que amanhã eu penso em você de novo.",
"Se dormir do seu lado fosse possível, eu não perdia tempo.",
"Boa noite pra pessoa mais linda que vai ler isso hoje.",
"A noite é sua cúmplice: é quando mais penso em você.",
"Boa noite! Fecha os olhos e imagina a gente junto.",
"Meu desejo antes de dormir: te ver amanhã.",
"Boa noite! Você é o sonho de que eu não quero acordar.",
"Se a saudade acordar de madrugada, a culpa é sua.",
"Boa noite pra você que deixa meus dias e noites melhores.",
"Vou dormir feliz só de saber que você leu isso.",
"Boa noite! Que a lua cuide dos seus sonhos — e de você.",
"Meu coração deu boa noite e sussurrou o seu nome.",
"Boa noite! Amanhã eu volto a te paquerar, prometo.",
"Se boa noite fosse beijo, eu te mandava um demorado.",
"Boa noite pra você que virou meu pensamento preferido.",
"Fecho os olhos e é você que aparece. Boa noite, meu bem.",
],
}

index = []
total = 0
counts = {}
for cid, name, emoji, grad in CATS:
    phrases = DATA.get(cid, []) + EXTRA.get(cid, []) + DATA_NEW.get(cid, [])
    # remove duplicatas mantendo a ordem
    seen = set()
    phrases = [p for p in phrases if not (p in seen or seen.add(p))]
    counts[cid] = len(phrases)
    total += len(phrases)
    with open(os.path.join(BASE, cid + ".json"), "w", encoding="utf-8") as f:
        json.dump(phrases, f, ensure_ascii=False, indent=2)
    index.append({"id": cid, "name": name, "emoji": emoji, "gradient": grad, "premium": False})

with open(os.path.join(BASE, "index.json"), "w", encoding="utf-8") as f:
    json.dump(index, f, ensure_ascii=False, indent=2)

print("Categorias:", len(CATS), "| Total cantadas:", total)
for cid, name, *_ in CATS:
    print(f"  {name}: {counts[cid]}")
