# -*- coding: utf-8 -*-
"""Gera o conteudo de CANTADAS (leves: fofas + engracadas) em assets/frases/.
Escreve index.json (categorias) + {id}.json (array de cantadas). Tudo autoral.
"""
import json, os

BASE = os.path.join(os.path.dirname(__file__), "..", "assets", "frases")
os.makedirs(BASE, exist_ok=True)

CATS = [
    ("fofas",       "Fofas",            "💕", ["#FF5F6D", "#FFC371"]),
    ("romanticas",  "Românticas",       "❤️", ["#e53935", "#e35d5b"]),
    ("engracadas",  "Engraçadas",       "😂", ["#f7971e", "#ffd200"]),
    ("criativas",   "Criativas",        "✨", ["#8E2DE2", "#4A00E0"]),
    ("nerds",       "Nerds & Geek",     "🤓", ["#2193b0", "#6dd5ed"]),
    ("de_bar",      "De Bar & Balada",  "🍻", ["#F09819", "#EDDE5D"]),
    ("elogios",     "Elogios",          "😍", ["#FF0080", "#FF8C00"]),
    ("atrevidas",   "Atrevidas",        "😏", ["#c31432", "#240b36"]),
    ("classicas",   "Clássicas",        "⭐", ["#FFB75E", "#ED8F03"]),
    ("para_crush",  "Para o Crush",     "💘", ["#FC466B", "#3F5EFB"]),
]

DATA = {
"fofas": [
"Você é a razão do meu sorriso bobo o dia inteiro.",
"Se aconchego fosse pessoa, teria o seu nome.",
"Você é fofo do jeitinho que eu sempre quis abraçar.",
"Meu lugar favorito no mundo é do seu ladinho.",
"Você deixa até os meus dias cinzas coloridos.",
"Queria ser o seu cobertor pra te abraçar a noite toda.",
"Com você, até o silêncio é gostoso.",
"Você é o carinho que eu não sabia que estava procurando.",
"Se eu pudesse, guardava o seu sorriso no bolso.",
"Você é a coisa mais fofa que apareceu na minha vida.",
"Meu coração faz um barulhinho fofo quando você chega.",
"Você é aquele abraço quentinho em forma de gente.",
"Do seu lado, o mundo fica mais macio.",
"Você é o motivo de eu acordar de bom humor.",
"Queria congelar o tempo só pra ficar mais um pouco com você.",
"Você é a fofura que faltava no meu dia.",
"Seu sorriso é o meu docinho preferido.",
"Você me dá aquela vontade de ficar de mãos dadas sem pressa.",
"Com você por perto, tudo fica mais leve.",
"Você é a definição de aconchego pra mim.",
"Meu coração escolheu você sem nem pedir minha permissão.",
"Você é fofo demais pra ser real, mas ainda bem que é.",
"Queria ser motivo do seu sorriso, igual você é do meu.",
"Você é a parte boa de todos os meus dias.",
"Se carinho tivesse rosto, seria o seu.",
"Você é aquele friozinho gostoso na barriga.",
"Do seu lado eu me sinto em casa.",
"Você é a fofura que eu quero na minha rotina.",
"Meu dia só fica completo depois do seu 'oi'.",
"Você é pequeno detalhe que faz toda a diferença em mim.",
"Queria te dar um abraço que durasse o dia inteiro.",
"Você é a ternura em pessoa.",
"Seu jeitinho me desarma toda vez.",
"Você é o meu cantinho preferido do universo.",
"Com você o coração fica quentinho.",
"Você é fofo até quando faz nada, imagina fazendo carinho.",
"Meu sorriso tem CPF e o nome dele é você.",
"Você é a razão de eu olhar o celular sorrindo.",
"Queria embrulhar você pra presente e ficar só pra mim.",
"Você é a fofura que arruma qualquer dia ruim.",
],
"romanticas": [
"Se eu tivesse uma estrela pra cada vez que penso em você, teria o céu inteiro.",
"Você chegou e o mundo fez sentido.",
"Meu coração bate em ritmo de você.",
"Você é o poema que eu não sabia escrever.",
"Se amar você é errado, não quero ter razão.",
"Você é o meu para sempre em forma de pessoa.",
"Meu lugar preferido é dentro de um abraço seu.",
"Você é o motivo de todas as minhas melhores histórias.",
"Se o amor tivesse endereço, seria onde você estivesse.",
"Você é a resposta pra perguntas que eu nem sabia que tinha.",
"Comigo é simples: onde você está, é onde eu quero estar.",
"Você é o tipo de amor que a gente escreve música.",
"Meu coração escolheu e não quer devolução.",
"Você é o sonho que ficou depois que eu acordei.",
"Se existe destino, o meu tinha o seu nome.",
"Você me faz acreditar em coisa que eu jurava não existir.",
"Meu mundo gira, mas sempre volta pra você.",
"Você é a razão de eu acreditar no amor de novo.",
"Contigo, até o comum vira inesquecível.",
"Você é a paz que eu procurava no meio do caos.",
"Meu coração te reconheceu antes mesmo de eu entender.",
"Você é o começo de tudo que eu quero pra mim.",
"Se amar tem preço, eu pago à vista por você.",
"Você é a melhor parte de todos os meus dias.",
"Meu coração tem seu nome escrito em letra bonita.",
"Você é o amor que eu quero envelhecer junto.",
"Do seu lado, o tempo passa e eu nem ligo.",
"Você é a única certeza no meio das minhas dúvidas.",
"Meu coração é seu, e nem quero de volta.",
"Você é o motivo de eu sorrir do nada.",
"Se pudesse pedir um desejo, pediria mais tempo com você.",
"Você é o amor que cabe em uma vida inteira.",
"Contigo eu aprendi que lar é uma pessoa.",
"Você é a razão do meu 'bom dia' virar 'bom demais'.",
"Meu coração não tem GPS, mas sempre acha o caminho até você.",
"Você é a poesia que eu quero ler todo dia.",
"Se o amor fosse cor, o seu pintava o meu mundo.",
"Você é o abraço que resolve qualquer dia difícil.",
"Meu coração te escolheu e bateu o martelo.",
"Você é o para sempre que eu quero começar hoje.",
],
"engracadas": [
"Você é ladrão? Porque roubou minha última bolacha do coração.",
"Seu pai é padeiro? Porque você é um pão... de mel.",
"Perdi meu número, me empresta o seu?",
"Você acredita em amor à primeira vista ou preciso passar de novo?",
"Se beleza desse cadeia, você pegava prisão perpétua.",
"Você é Wi-Fi? Porque senti uma conexão... e agora quero a senha.",
"Me belisca, porque você é bom demais pra ser verdade.",
"Você é Google? Porque tem tudo que eu tava procurando.",
"Cuidado ao andar, senão você tropeça no meu coração caído.",
"Seu nome é Trakinas? Porque abriu e eu já quero.",
"Você é açúcar? Porque tá deixando meu dia doce demais.",
"Me chama de calculadora, porque contigo eu só quero contar.",
"Você é estacionamento? Porque eu quero passar horas aqui.",
"Se você fosse fruta, seria um 'gata-melão'.",
"Você caiu do céu ou pulou pra chamar minha atenção?",
"Me dá seu CEP? Quero saber o caminho pro seu coração.",
"Você é boleto? Porque não sai da minha cabeça (nem da minha conta).",
"Seu sorriso tem garantia? Porque quero um pra vida toda.",
"Você é pizza? Porque eu te quero inteirinha, sem dividir.",
"Me empresta um mapa? Me perdi nos seus olhos.",
"Você é bateria de celular? Porque tá acabando comigo (de amor).",
"Se carência fosse crime, eu tava preso te olhando.",
"Você é semáforo? Porque quando te vejo, eu paro.",
"Me chama de CEP, porque eu quero fazer parte do seu endereço.",
"Você é ar-condicionado? Porque me deixou gelado quando passou.",
"Seu nome é uê-fai? Porque quero ficar conectado a você.",
"Você é lombada? Porque me fez reduzir a velocidade e olhar.",
"Me dá um desconto? Porque tô caro de tão apaixonado.",
"Você é micro-ondas? Porque esquentou meu coração em 30 segundos.",
"Seu pai é agricultor? Porque plantou um jardim no meu coração.",
"Você é espelho? Porque me vejo com você pro resto da vida.",
"Me chama de pilha, porque contigo eu não desligo.",
"Você é cafezinho? Porque me deixou aceso a noite toda.",
"Se você fosse verbo, seria irregular de tão especial.",
"Você é tomada? Porque senti uma corrente entre a gente.",
"Me dá teu horário? Quero marcar o resto da minha vida.",
"Você é elevador? Porque me elevou o astral só de aparecer.",
"Seu nome é geladeira? Porque quero te abrir toda vez que der fome de você.",
"Você é adesivo? Porque grudou na minha mente.",
"Me chama de professor, porque quero dar aula de como te amar.",
],
"criativas": [
"Se cada pensamento seu virasse estrela, o céu ficava pequeno.",
"Você é aquela ideia genial que aparece do nada e muda tudo.",
"Reescrevi o dicionário: agora 'perfeito' tem a sua foto.",
"Você é plot twist da melhor história que eu já vivi.",
"Se o universo fosse um livro, você seria meu capítulo favorito.",
"Você é o detalhe que os artistas passam a vida tentando pintar.",
"Inventei um novo idioma só pra descrever o seu sorriso.",
"Você é a nota que faltava pra minha música ficar completa.",
"Se eu fosse pintor, gastaria todas as cores em você.",
"Você é a metáfora que todo poeta sonha em encontrar.",
"Coloquei você na minha lista de coisas impossíveis de esquecer.",
"Você é o enredo que eu quero que nunca acabe.",
"Se pensamentos fossem mensagens, sua caixa lotava.",
"Você é a fórmula que a ciência ainda não explicou.",
"Reprogramei meu coração: agora ele só roda com você.",
"Você é obra de arte que ganhou vida e resolveu me encontrar.",
"Se a inspiração tivesse rosto, seria o seu.",
"Você é o verso solto que decidiu rimar comigo.",
"Criei um planeta novo só pra morar perto de você.",
"Você é o clique que faltava na minha melhor foto.",
"Se ideias fossem fogos, você seria o grand finale.",
"Você é o rascunho que virou minha melhor versão.",
"Coloquei 'você' como senha de tudo, porque é o que eu não esqueço.",
"Você é o experimento que deu certo de primeira.",
"Se sonhos tivessem trilha sonora, a sua seria minha favorita.",
"Você é a página em branco onde eu quero escrever o futuro.",
"Reinventei a roda só pra ela girar na sua direção.",
"Você é a peça que encaixou no quebra-cabeça que eu era.",
"Se pudesse patentear um sorriso, patenteava o seu.",
"Você é o brainstorm que só teve boas ideias.",
"Coloquei você no modo avião: agora só tenho olhos pra você.",
"Você é o algoritmo que sempre me recomenda felicidade.",
"Se a criatividade fosse rio, você seria minha nascente.",
"Você é o esboço que virou minha obra-prima.",
"Reescrevi meu roteiro e coloquei você em todas as cenas.",
"Você é a invenção que a humanidade ainda vai agradecer.",
"Se cada olhar seu fosse pincelada, eu era uma galeria.",
"Você é o easter egg escondido no melhor jogo da minha vida.",
"Coloquei uma legenda na minha vida: 'depois de você'.",
"Você é a ideia que eu quero desenvolver pra sempre.",
],
"nerds": [
"Você deve ser feito de cobre e telúrio, porque você é Cu-Te.",
"Se você fosse uma variável, seria a constante da minha felicidade.",
"Meu amor por você é exponencial, não tem limite.",
"Você é o meu 100 de vida no jogo mais difícil: a rotina.",
"Sem você, meu código dá erro de compilação.",
"Você é o boss final que eu não quero derrotar, quero namorar.",
"Se amor fosse largura de banda, a nossa seria fibra óptica.",
"Você é o easter egg mais fofo do meu jogo favorito.",
"Meu coração roda em loop infinito por você.",
"Você é a atualização que deixou minha vida mais rápida.",
"Se eu fosse um jogo, você seria minha vida extra.",
"Você é a chave privada que abre o meu coração.",
"Nosso amor tem uptime de 100%, nunca cai.",
"Você é o crossover que eu não sabia que precisava.",
"Se olhar fosse Wi-Fi, o seu tinha o sinal mais forte.",
"Você é o cheat code da minha felicidade.",
"Meu coração deu overclock quando você chegou.",
"Você é a run perfeita: sem bug e sem lag.",
"Se você fosse função, seria a que sempre retorna sorriso.",
"Você é o combo perfeito que eu levei a vida pra descobrir.",
"Meu amor por você não tem cooldown.",
"Você é a expansão que faltava na história da minha vida.",
"Se eu tivesse que salvar um checkpoint, seria ao seu lado.",
"Você é o loot lendário que dropou no meu caminho.",
"Nosso amor é open source: livre e pra sempre.",
"Você é a senha que meu coração nunca esquece.",
"Se cada byte fosse um beijo, eu te daria um terabyte.",
"Você é o respawn do meu bom humor.",
"Meu coração não tem antivírus contra você.",
"Você é a build perfeita que eu não quero mudar.",
"Se amor fosse pixel, você seria 4K.",
"Você é o portal que me leva pro melhor mundo.",
"Meu coração deu 'match' e não quer desfazer.",
"Você é a DLC que deixou minha vida completa.",
"Se você fosse comando, seria Ctrl+Z dos meus dias ruins.",
"Você é o high score que eu nunca vou superar.",
"Nosso amor não precisa de tutorial, veio intuitivo.",
"Você é o power-up que me deixou invencível.",
"Meu coração te deu admin: acesso total.",
"Você é o final feliz que todo bom jogo merece.",
],
"de_bar": [
"Sua beleza fez minha bebida gelada esquentar.",
"Deixa eu adivinhar seu nome: futuro?",
"Se sorriso fosse dose, você me deixava embriagado.",
"Vim aqui só pela cerveja, mas fiquei pelo seu sorriso.",
"Posso te pagar uma bebida ou você prefere ir direto pro plano de vida a dois?",
"Nesse bar cheio, meus olhos só acharam você.",
"Você é o petisco que faltava pra minha noite ficar completa.",
"Se eu fechar a conta, você fecha o dia comigo?",
"Sua risada é a melhor trilha sonora dessa balada.",
"Vim beber pra esquecer, mas agora só quero lembrar de você.",
"Se dançar fosse desculpa, eu inventava uma música só nossa.",
"Você é o brinde que eu quero fazer todas as noites.",
"O bar tá cheio, mas do seu lado sobra espaço pra gente.",
"Sua presença é mais forte que qualquer dose daqui.",
"Se a noite fosse jovem, eu apostava ela toda em você.",
"Você chegou e a balada ficou boa de verdade.",
"Deixa eu te tirar pra dançar antes que outro tenha a boa ideia.",
"Sua beleza não tá no cardápio, mas é a única coisa que eu quero.",
"Se eu perder essa noite, pelo menos ganhei seu sorriso.",
"Você é o motivo de eu não querer ir embora tão cedo.",
"Nessa música lenta, meu único pedido é você.",
"Se cada olhar seu fosse um drink, eu já tava apaixonado.",
"Vim pra pista, mas o melhor lance da noite é você.",
"Sua companhia vale mais que o happy hour inteiro.",
"Se a última música tocar, dança comigo até o fim?",
"Você é o after mais gostoso que essa noite podia ter.",
"Deixa eu adivinhar: você também não veio pela cerveja, né?",
"Sua risada abafou o som do bar inteiro.",
"Se eu te pagar um chopp, você me paga com um sorriso?",
"Você é o brinde que eu quero repetir a noite toda.",
"Nessa multidão, só a sua vibe me chamou.",
"Se dançar colado fosse crime, eu me entregava agora.",
"Você deixou a noite mais interessante que qualquer promoção.",
"Vim beber sozinho, mas do seu lado eu fico bem acompanhado.",
"Se a conta chegar, deixa que eu pago, só fica mais um pouco.",
"Sua energia é o melhor open bar dessa festa.",
"Você é o motivo de eu querer prolongar essa madrugada.",
"Se a balada acabar, a gente continua a noite conversando?",
"Sua presença deixou meu chopp de lado.",
"Você é o encontro que eu não planejei, mas não quero perder.",
],
"elogios": [
"Seu sorriso ilumina qualquer ambiente.",
"Você tem o olhar mais bonito que eu já vi.",
"Sua presença muda o clima de qualquer lugar.",
"Você é bonito por dentro e por fora, e isso é raro.",
"Seu jeito de falar prende qualquer um.",
"Você tem uma beleza que não cansa de olhar.",
"Sua energia contagia todo mundo em volta.",
"Você é o tipo de pessoa que a gente lembra pra sempre.",
"Seu sorriso deveria ser tombado como patrimônio.",
"Você tem um charme que não se aprende, se nasce com ele.",
"Sua voz é a coisa mais gostosa de ouvir.",
"Você é elegante até quando não tá tentando.",
"Seu olhar diz mais que mil palavras.",
"Você tem uma beleza que combina com bom coração.",
"Sua risada é a melhor coisa do meu dia.",
"Você é impossível de passar despercebido.",
"Seu estilo é único, ninguém copia.",
"Você tem um brilho próprio que chama atenção.",
"Sua simpatia conquista qualquer pessoa.",
"Você é bonito de um jeito que fica na memória.",
"Seu sorriso vale mais que qualquer palavra.",
"Você tem a beleza que a foto nunca consegue capturar direito.",
"Sua presença já melhora meu dia inteiro.",
"Você é o tipo de gente que deixa o mundo mais bonito.",
"Seu jeito doce combina com esse rosto lindo.",
"Você tem um magnetismo que não dá pra explicar.",
"Sua elegância aparece até nos gestos simples.",
"Você é bonito e ainda por cima gente boa, é injusto.",
"Seu olhar tem um poder que você nem imagina.",
"Você é a definição de charme natural.",
"Sua beleza vem acompanhada de uma vibe incrível.",
"Você deixa qualquer roupa mais bonita.",
"Seu sorriso desarma qualquer mau humor.",
"Você tem uma luz que atrai todo mundo.",
"Sua confiança te deixa ainda mais atraente.",
"Você é bonito de olhar e melhor ainda de conhecer.",
"Seu jeito de ser é tão bonito quanto o seu rosto.",
"Você tem o dom de deixar tudo mais interessante.",
"Sua beleza é daquelas que marcam época.",
"Você é, sem exagero, a pessoa mais bonita daqui.",
],
"atrevidas": [
"Se eu te chamar pra sair, você já vem decidido a me conquistar?",
"Cuidado com esse olhar, ele tá me deixando sem juízo.",
"Você tem noção do efeito que causa ou finge que não?",
"Se depender de mim, essa conversa não acaba tão cedo.",
"Seu sorriso é perigoso, devia vir com aviso.",
"Tô te avisando: é fácil se apaixonar por você.",
"Se você chegar mais perto, eu não respondo pelas batidas do meu coração.",
"Você mexe comigo de um jeito que nem tá no manual.",
"Adianta eu resistir ou já me rendo agora?",
"Seu charme tá jogando sujo comigo.",
"Se eu piscar, você promete não sumir?",
"Você tem cara de quem vai bagunçar meus planos, e eu tô gostando.",
"Cuidado, porque eu tô a um sorriso seu de me apaixonar.",
"Você é do tipo que a gente olha duas vezes e ainda quer a terceira.",
"Se essa química fosse aula, a gente ia gabaritar.",
"Tô achando que você caprichou só pra me deixar sem jeito.",
"Seu olhar tá me convidando pra um perrengue gostoso.",
"Você chegou e meu autocontrole pediu férias.",
"Se eu te disser o que tô pensando, você cora ou sorri?",
"Você tem toda a pinta de ser a minha melhor má ideia.",
"Cuidado ao sorrir assim, que eu tomo como sinal verde.",
"Você tá deixando difícil eu me comportar.",
"Se depender desse clima, a noite promete.",
"Você é o tipo de tentação que vale a pena.",
"Tô aqui tentando ser sério, mas você não ajuda.",
"Seu jeito atrevido combina demais com o meu.",
"Se você continuar me olhando assim, eu vou ter que agir.",
"Você tem um quê de proibido que me atrai demais.",
"Adianta eu fingir que não reparei em você? Acho que não.",
"Você joga charme e eu já tô perdendo o jogo.",
"Se eu chegar, você recua ou aceita o desafio?",
"Você tem uma energia que mexe com qualquer um, imagina comigo.",
"Tô tentando não sorrir, mas você complica tudo.",
"Seu olhar tem segundas intenções, e eu aprovo.",
"Você é a distração mais gostosa que eu já tive.",
"Se a gente continuar assim, a conversa vai longe.",
"Você chegou chegando, e eu gostei do plano.",
"Cuidado que eu tô ficando viciado nesse seu jeito.",
"Você tem talento pra me deixar sem palavras.",
"Se isso aqui é um jogo, eu quero perder pra você.",
],
"classicas": [
"Seu pai é ladrão? Porque roubou as estrelas e colocou nos seus olhos.",
"Você não está cansado de correr o dia todo pela minha cabeça?",
"Acredita em amor à primeira vista ou preciso passar de novo?",
"Se beleza fosse tempo, você seria a eternidade.",
"Você deve ser um dicionário, porque dá sentido à minha vida.",
"Me perdi... você pode me dar a direção do seu coração?",
"Seu nome é Google? Porque você tem tudo o que eu procuro.",
"Se eu pudesse reorganizar o alfabeto, colocaria o U e o EU juntos.",
"Você caiu do céu? Porque você é um anjo.",
"Deve doer... cair do céu assim, tão perfeito.",
"Se um beijo seu fosse floco de neve, eu te mandaria uma nevasca.",
"Você tem um mapa? Porque me perdi nos seus olhos.",
"Seu sorriso é a oitava maravilha do mundo.",
"Se olhar matasse, o seu me conquistava na hora.",
"Você é a resposta certa pra pergunta que eu nem sabia fazer.",
"Meu coração ligou dizendo que sente sua falta.",
"Se beleza desse multa, você já tava devendo pra mim.",
"Você é como o sol: ilumina tudo por onde passa.",
"Não sou fotógrafo, mas posso nos imaginar juntos.",
"Se eu fosse estrela, brilharia só pra você me notar.",
"Você é doce como mel e raro como diamante.",
"Cansei de procurar minha alma gêmea, aí você apareceu.",
"Seu sorriso poderia acabar com qualquer tristeza.",
"Se o amor fosse um livro, você seria minha história favorita.",
"Você é a razão de eu acreditar em contos de fada.",
"Meus olhos procuraram a vida toda e pararam em você.",
"Se cada estrela fosse um pensamento meu, o céu seria seu.",
"Você tem o dom de deixar tudo mais bonito.",
"Se eu tivesse um desejo, seria te ver sorrir todo dia.",
"Você é o tipo de sonho de que a gente não quer acordar.",
"Seu olhar tem o brilho que eu procurava.",
"Se amor fosse rio, o meu desaguava em você.",
"Você é a melhor coincidência da minha vida.",
"Seu sorriso é a chave do meu bom humor.",
"Se beleza fosse crime, você pegava perpétua.",
"Você é a estrela mais brilhante do meu céu.",
"Meu coração te reconheceu antes de eu entender.",
"Se eu pudesse, passava a vida inteira te olhando.",
"Você é o presente que eu não esperava ganhar.",
"Seu jeito me conquistou sem nem tentar.",
],
"para_crush": [
"Oi crush, meu dia melhora 100% quando você aparece.",
"Se um dia der, queria te levar pra tomar um sorvete.",
"Você não sai da minha cabeça desde que a gente se falou.",
"Confesso: eu curto quando você me responde rapidinho.",
"Toda vez que você posta, eu sorrio antes de curtir.",
"Se eu te chamar pra sair, você topa?",
"Você é o único motivo de eu ficar olhando o celular.",
"Crush, você reparou que a gente combina, ou sou só eu?",
"Queria ter coragem de te dizer o quanto eu te acho incrível.",
"Se depender de mim, essa amizade vira algo mais.",
"Você é o tipo de pessoa que eu queria conhecer melhor.",
"Confessa: você também sente esse clima entre a gente?",
"Meu 'visto' demora porque eu fico pensando na resposta perfeita.",
"Se você me chamasse pra sair, eu ia dizer sim na hora.",
"Crush, seu sorriso é o print que eu não apago.",
"Queria ser o motivo do seu sorriso hoje.",
"Você já reparou o quanto a nossa conversa flui?",
"Se eu pudesse escolher com quem passar o dia, seria você.",
"Confesso que crio expectativa toda vez que você digita.",
"Você é aquele crush que virou plano sério.",
"Queria saber se eu apareço nos seus pensamentos também.",
"Se a gente se conhecesse melhor, tenho certeza que ia dar certo.",
"Crush, você é a melhor notificação do meu dia.",
"Toda música de amor agora me lembra você.",
"Se você topar, eu já sei o lugar perfeito pro nosso primeiro encontro.",
"Você deixou de ser crush e virou vontade de tentar.",
"Confessa que você também dá uma olhadinha no meu perfil.",
"Queria transformar esses 'oi' em algo pra vida toda.",
"Crush, com você até conversa boba fica interessante.",
"Se eu te chamar hoje, você tem plano melhor que eu?",
"Você é o tipo de pessoa que vale a pena arriscar.",
"Confesso que fico feliz demais quando é você quem chama.",
"Queria ser motivo de você sorrir olhando o celular.",
"Crush, a gente ia formar um casal e tanto.",
"Se rolar, prometo caprichar no primeiro encontro.",
"Você virou aquele nome que eu procuro primeiro na tela.",
"Confessa que a gente tem uma química diferente.",
"Queria saber se você sente esse friozinho na barriga também.",
"Crush, tô aqui torcendo pra você me dar uma chance.",
"Se eu pudesse dar um match na vida real, seria com você.",
],
}

index = []
for cid, name, emoji, grad in CATS:
    phrases = DATA[cid]
    with open(os.path.join(BASE, cid + ".json"), "w", encoding="utf-8") as f:
        json.dump(phrases, f, ensure_ascii=False, indent=2)
    index.append({"id": cid, "name": name, "emoji": emoji, "gradient": grad, "premium": False})

with open(os.path.join(BASE, "index.json"), "w", encoding="utf-8") as f:
    json.dump(index, f, ensure_ascii=False, indent=2)

total = sum(len(DATA[c[0]]) for c in CATS)
print("Categorias:", len(CATS), "| Total cantadas:", total)
for cid, name, *_ in CATS:
    print(f"  {name}: {len(DATA[cid])}")
